[tool.poetry]
name = "langchain-chainlit-docker"
version = "0.1.0"
description = "A template langchain Chainlit App with Docker Deployments"
authors = ["Sudarshan Koirala"]
license = "MIT"
readme = "README.md"
packages = [{include = "langchain_chainlit_docker_deployment"}]


[tool.poetry.dependencies]
python = "^3.10"
langchain = "0.0.199"
openai = "0.27.8"
chainlit = "0.3.0"
pandas = "^2.0.3"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
